import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png"
  },
  // thumbnail preview
  openGraph: {
    title: "My Portfolio",
    description: "Check out my work and projects",
    url: "https://nazeeha.dev",
    siteName: "My Portfolio",
    images: [
      {
        url: "https://nazeeha.dev/preview.png",
        width: 1200,
        height: 630,
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "My Portfolio",
    description: "Check out my work and projects",
    images: ["https://nazeeha.dev/preview.png"],
  }
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children} <Analytics /> </body>
    </html>
  );
}
